v200409200800.  Platform UI's submission for I200409200800.  The following fixes are included: + Bug 32789. [EditorMgmt] Allow control of editor tab compression + Bug 49770. [About] no way to provide translated about.html files + Bug 56957. [Encoding] Reusable EncodingFieldEditor + Bug 57093. [Viewers] &quot;Widget is disposed&quot; when updating from CVS + Bug 63324. [ActionSets] Plugin not deactivated with Exception at startup() + Bug 68880. [Progress] NewProgressViewer uses hard coded colours + Bug 71445. [KeyBindings] Emacs key binding suggestion + Bug 72114. [ViewMgmt] Views that implement ISaveablePart are not consulted for dirty state before they are closed. + Bug 72217. CTabFolder should hide tabs in LRU order + Bug 72794. [Decorators] Hierarchy view shows wrong visibility for public method [type hierarchy] + Bug 73487. [Images] Update the workbench classes to use JFace's ImageCache + Bug 73660. [Preferences] Need to migrate to the OSGI API + Bug 73715. [Workbench] (regression) Workbench menus disappeared after closing the perspective + Bug 73795. [RCP] [KeyBindings] activeKeyConfiguration extension point doesn't work + Bug 73926. [Decorators] [RCP] NoClassDefFoundError: org/eclipse/ui/internal/progress/TaskInfo + Bug 73927. Optimize switching perspectives + Bug 73962. [IDE] NPE in CopyFilesAndFoldersOperation when overwriting existing folder + Bug 73993. [WorkingSets] Working sets schema must be more specific
The following projects have changed:
+ org.eclipse.jface
+ org.eclipse.ui
+ org.eclipse.ui.ide
+ org.eclipse.ui.tests
+ org.eclipse.ui.workbench